-- CreateTable
CREATE TABLE "Database" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Ad" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "databaseId" TEXT NOT NULL,
    "externalId" TEXT,
    "brand" TEXT,
    "primaryCategory" TEXT,
    "subCategory" TEXT,
    "niche" TEXT,
    "segment" TEXT,
    "platform" TEXT,
    "country" TEXT,
    "organicOrPaid" TEXT,
    "contentType" TEXT,
    "urlType" TEXT,
    "adLink" TEXT,
    "referenceUrl" TEXT,
    "backupSearchUrl" TEXT,
    "adLibraryUrl" TEXT,
    "adSnapshotUrl" TEXT,
    "advertiserPageUrl" TEXT,
    "destinationUrl" TEXT,
    "creativeVideoUrl" TEXT,
    "creativeImageUrl" TEXT,
    "urlReviewed" BOOLEAN,
    "hookType" TEXT,
    "hookExample" TEXT,
    "first3Seconds" TEXT,
    "formatType" TEXT,
    "visualStyle" TEXT,
    "personaTarget" TEXT,
    "scriptStructure" TEXT,
    "ctaType" TEXT,
    "creativeAngle" TEXT,
    "avatarOrCreativeType" TEXT,
    "adCopy" TEXT,
    "headline" TEXT,
    "description" TEXT,
    "offer" TEXT,
    "performanceScore" REAL,
    "hookScore" REAL,
    "retentionScore" REAL,
    "trustScore" REAL,
    "conversionIntentScore" REAL,
    "aiReplicabilityScore" REAL,
    "nicheTransferScore" REAL,
    "overallScore" REAL,
    "performanceProxyScore" REAL,
    "strategicPriority" INTEGER,
    "views" INTEGER,
    "likes" INTEGER,
    "comments" INTEGER,
    "shares" INTEGER,
    "impressions" INTEGER,
    "spend" REAL,
    "currency" TEXT,
    "engagementProxy" REAL,
    "whyItWorks" TEXT,
    "howToReplicate" TEXT,
    "aiAvatarAdaptation" TEXT,
    "valueForUs" TEXT,
    "replicationInstruction" TEXT,
    "useCaseForUs" TEXT,
    "complianceRisk" TEXT,
    "strategicTag" TEXT,
    "assetStatus" TEXT,
    "funnelStage" TEXT,
    "monetisationPath" TEXT,
    "notes" TEXT,
    "reviewStatus" TEXT DEFAULT 'unreviewed',
    "sourceActor" TEXT,
    "sourcePlatform" TEXT,
    "scrapedAt" DATETIME,
    "firstSeen" DATETIME,
    "lastSeen" DATETIME,
    "brandOrCreator" TEXT,
    "referenceTitle" TEXT,
    "referenceName" TEXT,
    "sourceType" TEXT,
    "priorityRank" INTEGER,
    "extraFields" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Ad_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ScrapeRun" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "actor" TEXT NOT NULL,
    "keyword" TEXT,
    "platform" TEXT,
    "status" TEXT NOT NULL,
    "rowCount" INTEGER,
    "cost" REAL,
    "rawDataPath" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE UNIQUE INDEX "Database_name_key" ON "Database"("name");
