
-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "Database" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Database_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Ad" (
    "id" TEXT NOT NULL,
    "databaseId" TEXT NOT NULL,
    "externalId" TEXT,
    "brand" TEXT,
    "primaryCategory" TEXT,
    "subCategory" TEXT,
    "niche" TEXT,
    "segment" TEXT,
    "platform" TEXT,
    "country" TEXT,
    "organicOrPaid" TEXT,
    "contentType" TEXT,
    "urlType" TEXT,
    "adLink" TEXT,
    "referenceUrl" TEXT,
    "backupSearchUrl" TEXT,
    "adLibraryUrl" TEXT,
    "adSnapshotUrl" TEXT,
    "advertiserPageUrl" TEXT,
    "destinationUrl" TEXT,
    "creativeVideoUrl" TEXT,
    "creativeImageUrl" TEXT,
    "urlReviewed" BOOLEAN,
    "hookType" TEXT,
    "hookExample" TEXT,
    "first3Seconds" TEXT,
    "formatType" TEXT,
    "visualStyle" TEXT,
    "personaTarget" TEXT,
    "scriptStructure" TEXT,
    "ctaType" TEXT,
    "creativeAngle" TEXT,
    "avatarOrCreativeType" TEXT,
    "adCopy" TEXT,
    "headline" TEXT,
    "description" TEXT,
    "offer" TEXT,
    "performanceScore" DOUBLE PRECISION,
    "hookScore" DOUBLE PRECISION,
    "retentionScore" DOUBLE PRECISION,
    "trustScore" DOUBLE PRECISION,
    "conversionIntentScore" DOUBLE PRECISION,
    "aiReplicabilityScore" DOUBLE PRECISION,
    "nicheTransferScore" DOUBLE PRECISION,
    "overallScore" DOUBLE PRECISION,
    "performanceProxyScore" DOUBLE PRECISION,
    "strategicPriority" INTEGER,
    "views" INTEGER,
    "likes" INTEGER,
    "comments" INTEGER,
    "shares" INTEGER,
    "impressions" INTEGER,
    "spend" DOUBLE PRECISION,
    "currency" TEXT,
    "engagementProxy" DOUBLE PRECISION,
    "whyItWorks" TEXT,
    "howToReplicate" TEXT,
    "aiAvatarAdaptation" TEXT,
    "valueForUs" TEXT,
    "replicationInstruction" TEXT,
    "useCaseForUs" TEXT,
    "complianceRisk" TEXT,
    "strategicTag" TEXT,
    "assetStatus" TEXT,
    "funnelStage" TEXT,
    "monetisationPath" TEXT,
    "notes" TEXT,
    "reviewStatus" TEXT DEFAULT 'unreviewed',
    "sourceActor" TEXT,
    "sourcePlatform" TEXT,
    "scrapedAt" TIMESTAMP(3),
    "firstSeen" TIMESTAMP(3),
    "lastSeen" TIMESTAMP(3),
    "brandOrCreator" TEXT,
    "referenceTitle" TEXT,
    "referenceName" TEXT,
    "sourceType" TEXT,
    "priorityRank" INTEGER,
    "extraFields" TEXT,
    "thumbnailUrl" TEXT,
    "painPoint" TEXT,
    "whyUseful" TEXT,
    "howAiShouldUseThis" TEXT,
    "usefulnessScore" DOUBLE PRECISION,
    "awarenessStage" TEXT,
    "desire" TEXT,
    "retentionStructure" TEXT,
    "primaryEmotionalTrigger" TEXT,
    "secondaryEmotionalTrigger" TEXT,
    "proofType" TEXT,
    "proofMechanism" TEXT,
    "viralityMechanic" TEXT,
    "creativeBucket" TEXT,
    "whyItLikelyWorked" TEXT,
    "whyItLikelyFailed" TEXT,
    "mainCreativePattern" TEXT,
    "winningHookPattern" TEXT,
    "retentionDevice" TEXT,
    "keyWeakness" TEXT,
    "bestReusableElement" TEXT,
    "suggestedVariationsToTest" TEXT,
    "recommendedNextCreativeTest" TEXT,
    "hookStrengthScore" DOUBLE PRECISION,
    "audienceSpecificityScore" DOUBLE PRECISION,
    "painClarityScore" DOUBLE PRECISION,
    "desireIntensityScore" DOUBLE PRECISION,
    "angleQualityScore" DOUBLE PRECISION,
    "messageClarityScore" DOUBLE PRECISION,
    "retentionQualityScore" DOUBLE PRECISION,
    "emotionalIntensityScore" DOUBLE PRECISION,
    "proofStrengthScore" DOUBLE PRECISION,
    "platformNativeFitScore" DOUBLE PRECISION,
    "shareabilityScore" DOUBLE PRECISION,
    "commentPotentialScore" DOUBLE PRECISION,
    "replicabilityScore" DOUBLE PRECISION,
    "aiAvatarAdaptabilityScore" DOUBLE PRECISION,
    "productionDifficultyScore" DOUBLE PRECISION,
    "complianceRiskScore" DOUBLE PRECISION,
    "organicViralPotential" DOUBLE PRECISION,
    "paidAdPotential" DOUBLE PRECISION,
    "aiReplicationValue" DOUBLE PRECISION,
    "overallUsefulnessScore" DOUBLE PRECISION,
    "taggingStatus" TEXT DEFAULT 'untagged',
    "aiTaggedAt" TIMESTAMP(3),
    "confidenceScore" DOUBLE PRECISION,
    "confidenceReason" TEXT,
    "usefulnessStatus" TEXT,
    "usefulnessReason" TEXT,
    "usefulnessConfidence" DOUBLE PRECISION,
    "recommendedAction" TEXT,
    "ingestionSource" TEXT,
    "ingestionKeyword" TEXT,
    "rawSourcePayload" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Ad_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ScrapeRun" (
    "id" TEXT NOT NULL,
    "actor" TEXT NOT NULL,
    "keyword" TEXT,
    "platform" TEXT,
    "status" TEXT NOT NULL,
    "rowCount" INTEGER,
    "cost" DOUBLE PRECISION,
    "rawDataPath" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ScrapeRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ImportJob" (
    "id" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "databaseId" TEXT NOT NULL,
    "databaseName" TEXT,
    "status" TEXT NOT NULL,
    "totalRows" INTEGER,
    "imported" INTEGER,
    "skipped" INTEGER,
    "failed" INTEGER,
    "deduped" INTEGER,
    "keyword" TEXT,
    "actor" TEXT,
    "errors" TEXT,
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ImportJob_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Database_name_key" ON "Database"("name");

-- AddForeignKey
ALTER TABLE "Ad" ADD CONSTRAINT "Ad_databaseId_fkey" FOREIGN KEY ("databaseId") REFERENCES "Database"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

